import type { Metadata } from "next";
import RootLayoutComponent from "@/components/root/RootLayoutComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <RootLayoutComponent>{children}</RootLayoutComponent>;
}
